apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      containers:
      - name: matching-service
        image: matching-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9092