apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-redis
spec:
  selector:
    matchLabels:
      app: my-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: my-redis
    spec:
      containers:
      - name: my-redis
        image: my-redis:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: my-redis
spec:
  type: NodePort
  selector:
    app: my-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379